---
galaxy_info:
  role_name: nginx
  author: ansix
  description: Nginx web server installation and configuration
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Amazon
      versions:
        - all

dependencies:
  - base