---
galaxy_info:
  role_name: ssh
  author: ansix
  description: SSH access configuration and key management
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Amazon
      versions:
        - all

dependencies:
  - base