---
galaxy_info:
  role_name: app
  author: ansix
  description: Static website application deployment
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Amazon
      versions:
        - all

dependencies:
  - base
  - nginx