---
galaxy_info:
  role_name: deployment
  author: ansix
  description: Complete server configuration and application deployment
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Amazon
      versions:
        - all

dependencies:
  - base
  - ssh
  - nginx
  - app