---
galaxy_info:
  role_name: base
  author: ansix
  description: Base system setup and utilities installation
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Amazon
      versions:
        - all

dependencies: []