---
# First play: Provision EC2 infrastructure
- name: Provision EC2 instance for web server
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../vars/aws-vars.yml
  
  roles:
    - { role: provisioning, tags: ["provision"] }

# Second play: Configure the newly created instance
- name: Configure web server on EC2 instance  
  hosts: webservers_dynamic
  become: true
  gather_facts: true
  vars_files:
    - ../vars/aws-vars.yml

  roles:
    - { role: deployment, tags: ["deploy"] }
