---
- name: Provision EC2 instance for web server
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../vars/aws-vars.yml
  
  roles:
    - { role: aws, tags: ["provision"] }

  post_tasks:
    - name: Refresh inventory to make sure new instances exist in inventory
      meta: refresh_inventory
      tags: ["provision"]